name: Triển khai Next.js lên GitHub Pages

on:
  push:
    branches:
      - main  # Thay 'main' bằng nhánh chính của bạn nếu khác

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Hoặc phiên bản Node.js bạn đang sử dụng

      - name: Cài đặt các phụ thuộc
        run: npm install

      - name: Xây dựng và xuất bản ứng dụng
        run: npm run deploy

      - name: Triển khai lên GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
        


